#!/bin/bash

PATH=$PATH:/usr/bin:/bin

file='/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:08/PNP0C09:00/ACPI0003:00/power_supply/AC/online'
sleep .5
current=$(cat $file)
if [ "$current" == "1" ]; then
  echo 11 > /sys/class/backlight/acpi_video0/brightness
else
  echo 8 > /sys/class/backlight/acpi_video0/brightness
fi
